openapi: "3.0.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: "http://localhost:5000/api/v1"
    description: "Local Development Environment"
paths:
  /users/test/{id}:
    get:
      summary: 'Provides search capability.'
      parameters:
        - name: id
          in: path
          description: ID of the user.
          required: true
          schema:
            type: number
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                    id: 
                      type: number
                      example: 4011,
                    title:
                      type: string
                      example: 'Latest report 2019'
                    created:
                      type: string
                      format: date-time
                    archived:
                      type: boolean
                      default: false
                    
        '404':
          description: No matching record found for the given criteria.
  